// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPTLW0QAgf5rs_fKUsPclFHHpiH0QqMXU',
    appId: '1:60243541943:web:2d0022da90c8ba12ae3232',
    messagingSenderId: '60243541943',
    projectId: 'smartbankingapp-b25a0',
    authDomain: 'smartbankingapp-b25a0.firebaseapp.com',
    storageBucket: 'smartbankingapp-b25a0.firebasestorage.app',
    measurementId: 'G-QYESEFRWQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFbxQ3hH_2-vJEl0Blpf_VRRNitEEDCQ',
    appId: '1:60243541943:android:f389fac68a0163eeae3232',
    messagingSenderId: '60243541943',
    projectId: 'smartbankingapp-b25a0',
    storageBucket: 'smartbankingapp-b25a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtIkfpX7f_UpC2tz4bKaejO-lUYJ0xNeA',
    appId: '1:60243541943:ios:32cc06b9f0977cbbae3232',
    messagingSenderId: '60243541943',
    projectId: 'smartbankingapp-b25a0',
    storageBucket: 'smartbankingapp-b25a0.firebasestorage.app',
    iosBundleId: 'com.example.smartBankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtIkfpX7f_UpC2tz4bKaejO-lUYJ0xNeA',
    appId: '1:60243541943:ios:32cc06b9f0977cbbae3232',
    messagingSenderId: '60243541943',
    projectId: 'smartbankingapp-b25a0',
    storageBucket: 'smartbankingapp-b25a0.firebasestorage.app',
    iosBundleId: 'com.example.smartBankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPTLW0QAgf5rs_fKUsPclFHHpiH0QqMXU',
    appId: '1:60243541943:web:fac5a0fa43012718ae3232',
    messagingSenderId: '60243541943',
    projectId: 'smartbankingapp-b25a0',
    authDomain: 'smartbankingapp-b25a0.firebaseapp.com',
    storageBucket: 'smartbankingapp-b25a0.firebasestorage.app',
    measurementId: 'G-3RF0R093M7',
  );
}
