name: smart_banking_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.0
  geolocator: ^14.0.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.2.5   # Matches firebase_core ^3.4.1 requirements
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  intl: ^0.18.0
  firebase_auth_web: ^5.5.4
  flutter_local_notifications: ^17.1.0
  background_fetch: ^1.2.1
  pdf: ^3.10.7
  printing: ^5.12.1
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0
  path_provider: ^2.1.1
  path: ^1.8.3
  firebase_storage: 12.4.6



  # ✅ Firebase dependencies (all compatible)
  firebase_messaging: ^15.2.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
